package com.queue.backend.organizations;

  import jakarta.persistence.*;
  import java.time.OffsetDateTime;
  import lombok.Getter;
  import lombok.NoArgsConstructor;
  import lombok.Setter;
  import org.hibernate.annotations.CreationTimestamp;

  @Entity
  @Table(name = "organization")
  @Getter
  @Setter
  @NoArgsConstructor
  public class Organization {

      @Id
      // IDENTITY jer sema kaze GENERATED BY DEFAULT AS IDENTITY -
      // sekvencu vodi Postgres, ne Hibernate.
      @GeneratedValue(strategy = GenerationType.IDENTITY)
      private Long id;

      @Column(nullable = false, length = 120)
      private String name;

      @Column(nullable = false, length = 60, unique = true)
      private String slug;

      // Vrijeme postavlja Hibernate pri insertu. DB default now() ostaje
      // kao mreza za rucne inserte iz psql-a.
      @CreationTimestamp
      @Column(name = "created_at", nullable = false, updatable = false)
      private OffsetDateTime createdAt;
  }