-- ============================================================
-- Queue Management System - pocetna sema
-- V1: organization, location, service, queue, ticket
-- ============================================================

-- Organizacija: vlasnik svega ostalog (dom zdravlja, banka, opstina).
CREATE TABLE organization (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    slug       VARCHAR(60)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_organization_slug UNIQUE (slug)
);


-- Lokacija: fizicka filijala. Public display ekran visi na lokaciji.
CREATE TABLE location (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    name            VARCHAR(120) NOT NULL,
    address         VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_location_organization
        FOREIGN KEY (organization_id) REFERENCES organization (id)
);

CREATE INDEX idx_location_organization ON location (organization_id);


-- Usluga: katalog onoga sto se radi, definisan jednom po organizaciji.
CREATE TABLE service (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    name                 VARCHAR(120) NOT NULL,
    avg_duration_minutes INT          NOT NULL DEFAULT 10,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_service_organization
        FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT uq_service_org_name UNIQUE (organization_id, name),
    CONSTRAINT ck_service_duration CHECK (avg_duration_minutes > 0)
);

CREATE INDEX idx_service_organization ON service (organization_id);


-- Red: ziva instanca usluge na konkretnoj lokaciji.
-- last_number je tacka nadmetanja koju V4 zakljucava.
CREATE TABLE queue (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id      BIGINT      NOT NULL,
    service_id       BIGINT      NOT NULL,
    prefix           VARCHAR(3)  NOT NULL,
    is_open          BOOLEAN     NOT NULL DEFAULT FALSE,
    last_number      INT         NOT NULL DEFAULT 0,
    last_number_date DATE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_queue_location
        FOREIGN KEY (location_id) REFERENCES location (id),
    CONSTRAINT fk_queue_service
        FOREIGN KEY (service_id) REFERENCES service (id),
    CONSTRAINT uq_queue_location_service UNIQUE (location_id, service_id),
    CONSTRAINT ck_queue_last_number CHECK (last_number >= 0)
);

CREATE INDEX idx_queue_location ON queue (location_id);


-- Ticket: jedan covjek u redu, jednog dana.
-- Tri vremenske oznake nose kompletnu V6 statistiku.
CREATE TABLE ticket (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id     BIGINT      NOT NULL,
    number       VARCHAR(10) NOT NULL,
    sequence_no  INT         NOT NULL,
    issued_date  DATE        NOT NULL,
    status       VARCHAR(20) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    called_at    TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_ticket_queue
        FOREIGN KEY (queue_id) REFERENCES queue (id),
    CONSTRAINT uq_ticket_queue_date_seq UNIQUE (queue_id, issued_date, sequence_no),
    CONSTRAINT ck_ticket_status CHECK (status IN (
        'WAITING', 'CALLED', 'SERVING', 'COMPLETED',
        'CANCELLED', 'NO_SHOW', 'SKIPPED'
    ))
);

-- Indeks za najcesci upit: "sljedeci koji ceka u ovom redu danas".
CREATE INDEX idx_ticket_next ON ticket (queue_id, issued_date, status, sequence_no);
