-- ============================================================
-- V2: korisnici i uloge
-- ============================================================

-- Tabela se zove app_user, a ne user: "user" je rezervisana rijec u
-- Postgresu i morala bi se svuda pisati pod navodnicima.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(160) NOT NULL,
    -- BCrypt hash je 60 znakova; 100 ostavlja mjesta ako se algoritam mijenja.
    -- Cista lozinka se NIKAD ne upisuje.
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN (
        'CUSTOMER', 'EMPLOYEE', 'MANAGER', 'ADMIN'
    ))
);

-- Login ide po emailu; UNIQUE constraint vec pravi indeks, pa dodatni ne treba.
