-- V5: RabbitMQ potrosaci.

-- Idempotency marker. Rabbit dostavlja "bar jednom": ako potrosac pukne
-- poslije pola posla, ista poruka stize ponovo. Prije obrade potrosac
-- upise (consumer, event_id) ovdje; ako red vec postoji, poruka je duplikat.
-- id = "<consumer>:<event_id>" - svaki potrosac obradjuje isti event
-- nezavisno, pa notifications i analytics imaju svaki svoj red.
CREATE TABLE processed_event (
    id           VARCHAR(120) PRIMARY KEY,
    processed_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Audit/statistika: jedan red po dogadjaju nad ticketom. Ulaz za V6
-- (prosjecno cekanje = called - created po redu/danu, itd.).
-- Namjerno denormalizovano (ticket_number, queue_id kopirani): statistika
-- se cita mnogo, a ne smije zavisiti od toga hoce li ticket kasnije biti
-- obrisan/arhiviran.
CREATE TABLE ticket_event_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(36)  NOT NULL,
    event_type    VARCHAR(20)  NOT NULL,   -- IZDAT / PROMIJENJEN
    ticket_id     BIGINT       NOT NULL,
    queue_id      BIGINT       NOT NULL,
    ticket_number VARCHAR(10)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,   -- status ticketa u trenutku dogadjaja
    occurred_at   TIMESTAMPTZ  NOT NULL,
    recorded_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Drugi sloj zastite od duplikata, ispod processed_event: cak i da
    -- guard zakaze, isti event ne moze dva puta u statistiku.
    CONSTRAINT uq_ticket_event_log_event UNIQUE (event_id)
);

-- V6 ce agregirati po redu i danu.
CREATE INDEX ix_ticket_event_log_queue_time ON ticket_event_log (queue_id, occurred_at);
